config/routes.rb
Rails.application.routes.draw do
  resources :money_transactions
  root  'money_transactions#index'
  get 'tags/:tag', to: 'money_transactions#index', as: "tag"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  self.primary_key = "id"
  has_many :money_transactions
  validates :id, presence: true
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  self.primary_key = "id"
  has_many :money_transactions
  validates :id, presence: true
  validates :name, presence: true
end

app/models/money_transaction.rb
class MoneyTransaction < ApplicationRecord
  belongs_to :money_transaction_type
  belongs_to :category
  belongs_to :account
  has_many :taggings
  has_many :tags, through: :taggings
  validates :money_transaction_type_id, presence: true
  validates :category_id, presence: true
  validates :account_id, presence: true

  #Search of tagged transactions
  def self.tagged_with(name)
    Rails.logger.debug "MoneyTransaction self.tagged_with(name): #{name}"
    Tag.find_by_name!(name).money_transactions
  end

  def transaction_prefix
    case money_transaction_type_id
    when 1
      "-"
    when 2
      "+"
    else
      "+/-"
    end
  end

  #setter attribute, returns selected tag names or creates them if non existing
  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create! #finds a record, if it doesn't exist, creates it
    end
  end

  #getter
  def all_tags
    self.tags.map(&:name).join(",")
  end
end

app/models/money_transaction_type.rb
class MoneyTransactionType < ApplicationRecord
  self.primary_key = "id"
  has_many :money_transactions
  validates :id, presence: true
  validates :name, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :money_transactions, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :money_transaction
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/money_transactions_controller.rb
class MoneyTransactionsController < ApplicationController
  before_action :set_money_transaction, only: [:show, :edit, :update, :destroy]

  # GET /money_transactions
  # GET /money_transactions.json
  def index
    # If tag exists (from search) find by that name
    if params[:tag]
      @money_transactions = MoneyTransaction.tagged_with(params[:tag])
    else
      @money_transactions = MoneyTransaction.all
    end
    @income_transactions = @money_transactions.where(money_transaction_type: 2)
    @expense_transactions = @money_transactions.where(money_transaction_type: 1)
    @transfer_transactions = @money_transactions.where(money_transaction_type: 3)
  end

  # GET /money_transactions/1
  # GET /money_transactions/1.json
  def show
  end

  # GET /money_transactions/new
  def new
    @money_transaction = MoneyTransaction.new
  end

  # GET /money_transactions/1/edit
  def edit
  end

  # POST /money_transactions
  # POST /money_transactions.json
  def create
    @money_transaction = MoneyTransaction.new(money_transaction_params)

    respond_to do |format|
      if @money_transaction.save
        format.html { redirect_to @money_transaction, notice: 'money_transaction was successfully created.' }
        format.json { render :show, status: :created, location: @money_transaction }
      else
        format.html { render :new }
        format.json { render json: @money_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /money_transactions/1
  # PATCH/PUT /money_transactions/1.json
  def update
    respond_to do |format|
      if @money_transaction.update(money_transaction_params)
        format.html { redirect_to @money_transaction, notice: 'money_transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @money_transaction }
      else
        format.html { render :edit }
        format.json { render json: @money_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /money_transactions/1
  # DELETE /money_transactions/1.json
  def destroy
    @money_transaction.destroy
    respond_to do |format|
      format.html { redirect_to money_transactions_url, notice: 'money_transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_money_transaction
    @money_transaction = MoneyTransaction.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def money_transaction_params
    params.require(:money_transaction).permit(:date, :value, :description, :category_id, :account_id, :money_transaction_type_id, :all_tags)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/money_transactions_helper.rb
module MoneyTransactionsHelper
  #hold the logic of converting the tags to links (look: _money_transaction.html.erb)
  def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ")
  end

  def transaction_link(money_transaction)
    link_to (money_transaction.category.name + " (" + money_transaction.transaction_prefix + money_transaction.value.to_s) + " kn)", money_transaction_path(money_transaction)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/money_transactions/_form.html.erb
<%= form_for(money_transaction, remote: true) do |f| %>
  <% if money_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(money_transaction.errors.count, "error") %> prohibited this money_transaction from being saved:</h2>

      <ul>
      <% money_transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date, id: "datepicker" %>
  </div>

  <div class="field">
    <%= f.label :money_transaction_type %>
    <%= f.collection_select :money_transaction_type_id, MoneyTransactionType.all, :id, :name %>
  </div>

  <div class="large-10 large-centered columns">
    <%= f.text_field :all_tags, placeholder: "Tags separated with comma" %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :account %>
    <%= f.collection_select :account_id, Account.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :value %>
    <%= f.text_field :value %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script>
  $('#datepicker').datepicker({format: 'dd.mm.yyyy'});
</script>

app/views/money_transactions/_money_transaction.html.erb
<%= div_for money_transaction do %>
  <div class="large-12 columns border border-box glassy-bg mt pt">
    <strong><%= h(transaction_link(money_transaction)) %></strong><br />
    <sup class="text-muted">From <%= time_ago_in_words(money_transaction.date)%></sup><br />
    <div class="mb pb">
      <%= h(money_transaction.account.name) %>
    </div>
    <div class="tags">
      <%=raw tag_links(money_transaction.all_tags) %>
    </div>
  </div>
<% end %>

app/views/money_transactions/_new.html.erb
<div class="row text-center">
  <%= form_for(MoneyTransaction.new, remote: true) do |f| %>
    <div class="large-5 large-centered columns">
      <%= f.text_field :date, id: "datepicker", placeholder: "Date" %>
    </div>

    <div class="large-5 large-centered columns">
      <%= f.label :money_transaction_type %>
      <%= f.collection_select :money_transaction_type_id, MoneyTransactionType.all, :id, :name %>
    </div>

    <div class="large-5 large-centered columns">
      <%= f.text_field :all_tags, placeholder: "Tags separated with comma" %>
    </div>

    <div class="large-5 large-centered columns">
      <%= f.label :category %>
      <%= f.collection_select :category_id, Category.all, :id, :name %>
    </div>

    <div class="large-5 large-centered columns">
      <%= f.label :account %>
      <%= f.collection_select :account_id, Account.all, :id, :name %>
    </div>

    <div class="large-5 large-centered columns">
      <%= f.text_field :value, placeholder: "Value in kn" %>
    </div>

    <div class="large-5 large-centered columns">
      <%= f.text_field :description, placeholder: "Payment description" %>
    </div>
    <div class="large-5 large-centered columns">
      <%= f.submit "MoneyTransaction", class: "button"%>
    </div>
  <% end %>
</div>
<script>
  $('#datepicker').datepicker({format: 'dd.mm.yyyy'});
</script>

app/views/money_transactions/create.js.erb
var new_money_transaction = $("<%= escape_javascript(render(partial: @money_transaction))%>").hide();
$('#money_transactions').prepend(new_money_transaction);
$('#money_transaction_<%= @money_transaction.id %>').fadeIn('slow');
$('#new_money_transaction')[0].reset();

app/views/money_transactions/edit.html.erb
<h1>Editing money transaction</h1>

<%= render 'form', money_transaction: @money_transaction %>

<%= link_to 'Show', @money_transaction %> |
<%= link_to 'Back', money_transactions_path %>

app/views/money_transactions/index.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
</head>

<p id="notice"><%= notice %></p>

<div class="row mt pt">
  <div class="large-5 columns">
    <div class="top-pad glassy-bg">
      <%= render partial: "money_transactions/new" %>
    </div>
  </div>
  <div class= "large-7 columns" id="money_transactions">
    <%= render partial: @money_transactions.reverse %>
  </div>
</div>

<h1>Money transactions</h1>
<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th>Date</th>
      <th>Type</th>
      <th>Category</th>
      <th>Account</th>
      <th>Value</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tfoot>
    <tr>
      <td>Income:</td>
      <td><%= @income_transactions.sum(:value) %></td>
    </tr>
    <tr>
      <td>Expences:</td>
      <td><%= @expense_transactions.sum(:value) %></td>
    </tr>
    <tr>
      <td>Net value:</td>
      <td><%= @income_transactions.sum(:value) - @expense_transactions.sum(:value) %></td>
    </tr>
  </tfoot>

  <tbody>
    <% @money_transactions.each do |money_transaction| %>
      <tr>
        <td><%= money_transaction.date %></td>
        <td><%= money_transaction.money_transaction_type.nil? ? "N/A" : money_transaction.money_transaction_type.name %></td>
        <td><%= money_transaction.category.nil? ? "N/A" : money_transaction.category.name %></td>
        <td><%= money_transaction.account.nil? ? "N/A" : money_transaction.account.name %></td>
        <td><%= money_transaction.value %></td>
        <td><%= money_transaction.description %></td>
        <td><%= link_to 'Show', money_transaction %></td>
        <td><%= link_to 'Edit', edit_money_transaction_path(money_transaction) %></td>
        <td><%= link_to 'Destroy', money_transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <tr>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'Add money transaction', new_money_transaction_path %>

app/views/money_transactions/new.html.erb
<h1>New money transaction</h1>

<%= render 'form', money_transaction: @money_transaction %>

<%= link_to 'Back', money_transactions_path %>

app/views/money_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @money_transaction.date %>
</p>

<p>
  <strong>Type:</strong>
  <%= @money_transaction.money_transaction_type.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @money_transaction.category.name %>
</p>

<p>
  <strong>Account:</strong>
  <%= @money_transaction.account.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @money_transaction.value %>
</p>

<p>
  <strong>Description:</strong>
  <%= @money_transaction.description %>
</p>

<%= link_to 'Edit', edit_money_transaction_path(@money_transaction) %> |
<%= link_to 'Back', money_transactions_path %>